apiVersion: v1
kind: Secret
metadata:
  name: datalake-provisioner-secrets
  namespace: datalake
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres.datalake.svc.cluster.local:5432/datalake?sslmode=disable"
  INTERNAL_TOKEN: "change-me"

  RGW_ACCESS_KEY_ID: "replace-me"
  RGW_SECRET_ACCESS_KEY: "replace-me"
