apiVersion: v1
kind: Service
metadata:
  name: datalake-provisioner
  namespace: datalake
  labels:
    app: datalake-provisioner
spec:
  type: ClusterIP
  selector:
    app: datalake-provisioner
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
