apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalake-provisioner.fullname" . }}-secret
  labels:
    {{- include "datalake-provisioner.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-postgres:5432/%s?sslmode=disable" .Values.postgres.user .Values.postgres.password (include "datalake-provisioner.fullname" .) .Values.postgres.db | quote }}
  INTERNAL_TOKEN: {{ .Values.provisioner.internalToken | quote }}

  RGW_ACCESS_KEY_ID: {{ .Values.provisioner.rgwAccessKeyId | quote }}
  RGW_SECRET_ACCESS_KEY: {{ .Values.provisioner.rgwSecretAccessKey | quote }}
